- src/com/joshdholtz/sentry/Sentry.java
adds support for setting user in Sentry entries to better help users debug their exceptions
> Add support for setting user

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
Fixes #33 
These attributes are listed here on the Sentry page:
https://docs.getsentry.com/hosted/clientdev/attributes/
> Add `setRelease`

- sentry-android/build.gradle
> Remove ununsed import and dropped minSdkVersion to 3

- sentry-android/src/main/AndroidManifest.xml
> Removed application definition from manifest

- sentry-android/sentry-android.iml
- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
- sentry-app/sentry-app.iml
- sentry-app/src/main/java/com/joshdholtz/sentryapp/MainActivity.java
- sentry-app/src/main/res/layout/activity_main.xml
Trying proposed changes from @amiraliakbari :heart:
> Fixes for weird crashing on file system stuffs

- README.md
Sorry... just saw it and figured might as well correct it.
> JSONObject typo.

- .idea/encodings.xml
- .idea/gradle.xml
- .idea/vcs.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- sentry-android/sentry-android.iml
- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
- sentry-app/build.gradle
- sentry-app/sentry-app.iml
- sentry-app/src/main/java/com/joshdholtz/sentryapp/MainActivity.java
> Self-hosted instances now parse DNS correctly

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
Add 3 types on context to events:
- device (built-in)
- os (built-in)
- package (custom)
Fixes #59 
The docs on context are here: https://docs.getsentry.com/hosted/clientdev/interfaces/#context-types
> Add device context to events

- README.md
- sentry-android/build.gradle
- sentry-android/sentry-android.iml
- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
- sentry-app/sentry-app.iml
- sentry-app/src/main/java/com/joshdholtz/sentryapp/MainActivity.java
Should fix #57 
I uploaded an APK with this version to Google Play and did not receive the error/warning that everyone was getting in #57
> Stop leaking credentials warning

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
Clean up some warnings produced by Android Studio. Mostly about redundant catch statements. This nukes 21 lines of code :clap:
> Clean up some build warnings produced in Android Studio

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
> Send device context in uncaught exception handler

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
I have not been able to reproduce this but it should fix the issue.
Fixes #69
> Fix JSON serialization on older API levels.

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
- Create a data class to store AppInfo. Ensure this is never null.
- Replace multiple calls to Sentry.getInstance() with a single call.
- Use StringBuilder to make headers
- sentry_timestamp header is not required - https://github.com/getsentry/sentry/issues/866
> Clean up some app version handling.

- README.md
- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
- sentry-app/src/main/java/com/joshdholtz/sentryapp/MainActivity.java
I've tried to keep the API as high-level as possible, and not expose too
much to the user.
Fixes #70
> Add breadcrumb support

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
> Fix bug when no network permission

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
Also make some cosmetic changes to how the date formatter is initialized
to make testing a little easier.
> Improve error logging when serialization fails

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
The aim here is to refactor things to make #98 into a much smaller
change than it is now.
I'm going to move as much state as I can into final non-null member
variables.
> Remove some uses of the InternalStorage singleton.

- README.md
- sentry-android/build.gradle
@joshdholtz can you cut a release if you get time please? no rush at all. these are minor changes.
> 1.5.2 release

- README.md
It will help beginners like me :)
> Add import to readme

- README.md
- sentry-android/build.gradle
- sentry-android/src/androidTest/java/com/joshdholtz/sentry/SentryEventBuilderTest.java
- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
- sentry-app/src/main/java/com/joshdholtz/sentryapp/MainActivity.java
> Add limits to Breadcrumb length

- README.md
- app/build.gradle
- sentry-android/build.gradle
- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
- sentry-app/build.gradle
- sentry-app/src/main/java/com/joshdholtz/sentryapp/MainActivity.java
Replace with the built-in HttpUrlConnection
This is a work-in-progress.
Addresses some of https://github.com/joshdholtz/Sentry-Android/issues/83
> Remove the org.apache http library

- sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java
> Added API to set environment in SentryEventBuilder.

- sentry-android/build.gradle
Most likely some copy+paste leftover for scm info.
> Fix scm pom info
